title: 김동준의 홈페이지
footer: '@Copyright 김동준의 홈페이지'
description: 평범한 컴퓨터 공학과 학생
site_title: '@kkdonjuun122 - 김동준의 홈페이지'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: kkdonjuun122
#blog_url: https://www.nagekar.com
email: 20202845@gm.hannam.ac.kr
#keybase_username: abhn
#twitter_username: abhn_
#reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp2.jpg

# Google Analytics ID
google_analytics: 